<?php

namespace AlexaPHP\Tests;

use ErrorException;
use PHPUnit_Framework_TestCase;

abstract class TestCase extends PHPUnit_Framework_TestCase
{
	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		set_error_handler(function($errno, $errstr, $errfile, $errline, array $errcontext) {
			// error was suppressed with the @-operator
			if (0 === error_reporting()) {
				return false;
			}

			throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
		});

		date_default_timezone_set('UTC');
	}
}
